# Generated by Django 5.1.4 on 2025-04-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="faq.faqcategory",
                verbose_name="Category",
            ),
        ),
    ]
