# Generated by Django 5.1.4 on 2025-04-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_alter_faq_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqcategory",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Category Title"),
        ),
    ]
