# Generated by Django 5.1.4 on 2025-04-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0003_alter_faqcategory_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQCategoryTrans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=100, verbose_name="CategoryTitle (English)"
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=100, verbose_name="CategoryTitle (Persian)"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=100, verbose_name="CategoryTitle (Arabic)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAQTrans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_en",
                    models.CharField(max_length=255, verbose_name="Question (English)"),
                ),
                (
                    "question_fa",
                    models.CharField(max_length=255, verbose_name="Question (Persian)"),
                ),
                (
                    "question_ar",
                    models.CharField(max_length=255, verbose_name="Question (Arabic)"),
                ),
                ("answer_en", models.TextField(verbose_name="Answer (English)")),
                ("answer_fa", models.TextField(verbose_name="Answer (Persian)")),
                ("answer_ar", models.TextField(verbose_name="Answer (Arabic)")),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Time Created"
                    ),
                ),
                (
                    "datetime_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date Time Modified"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="faq.faqcategorytrans",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
    ]
