# Generated by Django 5.1.4 on 2025-01-20 18:50

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=255, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="address",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="accounts.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="Postal Code"),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(max_length=255, verbose_name="Province"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="OM", verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
