# Generated by Django 5.1.4 on 2025-02-26 17:11

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_address_city_alter_address_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="OM", verbose_name="Phone Number"
            ),
        ),
    ]
