# Generated by Django 5.1.4 on 2025-02-25 13:19

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_alter_address_city_alter_address_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region="OM",
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "order_note",
                    models.CharField(blank=True, max_length=700, verbose_name="Note"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("p", "Paid"), ("u", "Unpaid"), ("c", "Canceled")],
                        default="u",
                        max_length=1,
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Time Created"
                    ),
                ),
                (
                    "datetime_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date Time Modified"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
    ]
