# Generated by Django 5.1.4 on 2025-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="authority",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Authority"
            ),
        ),
    ]
