# Generated by Django 5.1.4 on 2025-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Reference ID"
            ),
        ),
    ]
