# Generated by Django 5.1.4 on 2025-03-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_data_order_ref_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=3, max_digits=7, verbose_name="Price"
            ),
        ),
    ]
