# Generated by Django 5.1.4 on 2025-01-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
