# Generated by Django 5.1.4 on 2025-01-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_unit_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discounts",
        ),
    ]
