# Generated by Django 5.1.4 on 2025-01-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_discounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discounts",
            field=models.ManyToManyField(blank=True, to="products.discount"),
        ),
    ]
