# Generated by Django 5.1.4 on 2025-01-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="datatime_created",
            new_name="datetime_created",
        ),
    ]
