# Generated by Django 5.1.4 on 2025-01-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_rename_datatime_created_comment_datetime_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("w", "Waiting"), ("a", "Approved"), ("na", "Not Approved")],
                default="w",
                max_length=2,
            ),
        ),
    ]
