# Generated by Django 5.1.4 on 2025-01-20 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_comment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="category",
            name="top_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="products.product",
                verbose_name="Top Product",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="Comment Text"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Time Created"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="datetime_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date Time Modified"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.CharField(
                choices=[
                    ("1", "Very Bad"),
                    ("2", "Bad"),
                    ("3", "Normal"),
                    ("4", "Good"),
                    ("5", "Perfect"),
                ],
                max_length=10,
                verbose_name="Product Rating",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("w", "Waiting"), ("a", "Approved"), ("na", "Not Approved")],
                default="w",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="discount",
            field=models.FloatField(verbose_name="Discount"),
        ),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Time Created"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="datetime_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date Time Modified"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounts",
            field=models.ManyToManyField(
                blank=True, to="products.discount", verbose_name="Discount"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Inventory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Short Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=3, max_digits=6, verbose_name="Price"
            ),
        ),
    ]
