# Generated by Django 5.1.4 on 2025-01-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("w", "Waiting"), ("a", "Approved"), ("na", "Not Approved")],
                default="a",
                max_length=2,
                verbose_name="Status",
            ),
        ),
    ]
