# Generated by Django 5.1.4 on 2025-01-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_comment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=3, max_digits=7, verbose_name="Price"
            ),
        ),
    ]
