# Generated by Django 5.1.4 on 2025-01-24 14:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Description"),
        ),
    ]
