# Generated by Django 5.1.4 on 2025-01-24 15:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=ckeditor.fields.RichTextField(verbose_name="Comment Text"),
        ),
    ]
