# Generated by Django 5.1.4 on 2025-01-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="product/product_cover/",
                verbose_name="Product image",
            ),
        ),
    ]
