# Generated by Django 5.1.4 on 2025-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_remove_category_description_category_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
