# Generated by Django 5.1.4 on 2025-02-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_category_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="category",
            name="top_product",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Description"
            ),
        ),
    ]
