# Generated by Django 5.1.4 on 2025-02-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0018_remove_category_parent_remove_category_top_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.IntegerField(
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "Good"),
                    (5, "Perfect"),
                ],
                max_length=10,
                verbose_name="Product Rating",
            ),
        ),
    ]
