# Generated by Django 5.1.4 on 2025-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_alter_comment_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.IntegerField(
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "Good"),
                    (5, "Perfect"),
                ],
                verbose_name="Product Rating",
            ),
        ),
    ]
