# Generated by Django 5.1.4 on 2025-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_alter_comment_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Product Name"
            ),
        ),
    ]
